---
language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-platform-24.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
  licenses:
    - 'android-.*'
    - 'android-sdk-license-.+'
jdk:
  - oraclejdk8
notifications:
      email: true
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - mkdir -p "$ANDROID_SDK/licenses" || true
  - touch "$ANDROID_SDK/licenses/android-sdk-license"
  - touch "$ANDROID_SDK/licenses/android-sdk-preview-license"
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_SDK/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_SDK/licenses/android-sdk-preview-license"
  - 'chmod +x gradlew'
script:
  - './gradlew test' # Run unit tests
